flowchart TD
    korallo_dpd_spakowane --> korallo_dpd_wyslane
    korallo_inpost_spakowane --> korallo_inpost_wyslane
    labera_dpd_spakowane --> labera_dpd_wyslane
    labera_inpost_spakowane --> labera_inpost_wyslane
    korallo_dpd --> wyslane_przez_magento
    korallo_inpost --> wyslane_przez_magento
    laczenie_zamowien --> wyslane_przez_magento
    korallo_dpd_wyslane --> zakonczone
    korallo_inpost_wyslane --> zakonczone
    labera_dpd_wyslane --> zakonczone
    labera_inpost_wyslane --> zakonczone
    czesciowo_spakowane --> korallo_dpd_spakowane
    czesciowo_spakowane --> korallo_inpost_spakowane
    czesciowo_spakowane --> korallo_odbior_osobisty_gotowe
    czesciowo_spakowane --> labera_dpd_spakowane
    czesciowo_spakowane --> labera_inpost_spakowane
    czesciowo_spakowane --> labera_odbior_osobisty_gotowe
    korallo_dpd_wyslane --> czesciowo_wyslane
    korallo_inpost_wyslane --> czesciowo_wyslane
    korallo_odbior_osobisty_gotowe --> czesciowo_wyslane
    labera_dpd_wyslane --> czesciowo_wyslane
    labera_inpost_wyslane --> czesciowo_wyslane
    labera_odbior_osobisty_gotowe --> czesciowo_wyslane
    zrealizowano_zwrot_platnosci --> zakonczone
    new --> oczekuje_na_platnosc
    new --> oplacone
    oczekuje_na_platnosc --> oplacone
    oczekuje_na_platnosc --> anulowane
    oczekuje_na_platnosc --> wyslane_przez_magento
    oczekuje_na_platnosc --> korallo_dpd
    oplacone --> korallo_dpd
    oczekuje_na_platnosc --> labera_dpd
    oplacone --> labera_dpd
    oplacone --> korallo_dpd
    oplacone --> korallo_dpd_express
    oplacone --> korallo_inpost
    oplacone --> korallo_odbior_osobisty
    oplacone --> labera_dpd
    oplacone --> labera_dpd_express
    oplacone --> labera_inpost
    oplacone --> labera_odbior_osobisty
    korallo_dpd --> korallo_kolejka
    korallo_dpd_express --> korallo_zbieranie
    korallo_inpost --> korallo_kolejka
    korallo_odbior_osobisty --> korallo_zbieranie
    korallo_zbieranie --> korallo_pakowanie
    labera_dpd --> labera_kolejka
    labera_inpost --> labera_kolejka
    labera_odbior_osobisty --> labera_zbieranie
    labera_zbieranie --> labera_pakowanie
    korallo_pakowanie --> korallo_dpd_spakowane
    korallo_pakowanie --> korallo_inpost_spakowane
    korallo_pakowanie --> korallo_odbior_osobisty_gotowe
    labera_pakowanie --> labera_dpd_spakowane
    labera_pakowanie --> labera_inpost_spakowane
    labera_pakowanie --> labera_odbior_osobisty_gotowe
    oplacone --> laczenie_zamowien

