<?php

namespace Tests\Feature\Csv\Boxtop\Stock;
use PHPUnit\Framework\Attributes\Test;
use App\User;
use Tests\TestCase;

class IndexTest extends TestCase
{
    protected string $uri = '';

    protected User $user;

    protected function setUp(): void
    {
        parent::setUp();
        $this->user = User::factory()->create();
    }

    #[Test]
    public function test_if_uri_set(): void
    {
        $this->markTestIncomplete('This test was generated by "php artisan app:generate-routes-tests" call');

        $this->assertNotEmpty($this->uri);
    }

    #[Test]
    public function test_guest_call(): void
    {
        $this->markTestIncomplete('This test was generated by "php artisan app:generate-routes-tests" call');

        $response = $this->get($this->uri);

        $response->assertRedirect('/login');
    }

    #[Test]
    public function test_user_call(): void
    {
        $this->markTestIncomplete('This test was generated by "php artisan app:generate-routes-tests" call');

        $this->actingAs($this->user, 'web');

        $response = $this->get($this->uri);

        $response->assertForbidden();
    }

    #[Test]
    public function test_admin_call(): void
    {
        $this->markTestIncomplete('This test was generated by "php artisan app:generate-routes-tests" call');

        $this->user->assignRole('admin');

        $this->actingAs($this->user, 'web');

        $response = $this->get($this->uri);

        $response->assertForbidden();
    }
}
