name: Laravel Dusk Tests

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  dusk:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, pdo, pdo_mysql, sqlite, pdo_sqlite, bcmath, json, xml, curl, zip

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: |
        composer validate --strict || composer update --no-scripts
        composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Create SQLite test database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run migrations
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate --force

    - name: Install NPM dependencies
      run: npm ci

    - name: Build frontend assets
      run: npm run build

    - name: Upgrade Chrome Driver
      run: |
        php artisan dusk:chrome-driver --detect
        chmod +x ./vendor/laravel/dusk/bin/chromedriver-linux

    - name: Start Chrome Driver
      run: |
        ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
        sleep 5
        curl http://127.0.0.1:9515/status || exit 1

    - name: Start Laravel Server
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        APP_URL: http://127.0.0.1:8000
      run: php artisan serve --no-reload &

    - name: Wait for server
      run: |
        for i in {1..30}; do
          if curl -s http://127.0.0.1:8000 > /dev/null; then
            echo "Server is up"
            break
          fi
          echo "Waiting for server... ($i/30)"
          sleep 1
        done

    - name: Run Dusk Tests
      env:
        APP_URL: http://127.0.0.1:8000
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        DUSK_HEADLESS_DISABLED: false
        DUSK_DRIVER_URL: http://127.0.0.1:9515
      run: php artisan dusk

    - name: Upload Screenshots
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: dusk-screenshots
        path: tests/Browser/screenshots

    - name: Upload Console Logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: dusk-console
        path: tests/Browser/console

    - name: Upload Laravel Logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: laravel-logs
        path: storage/logs