name: PHPUnit Tests
on: [push]

env:
  APP_URL: "http://127.0.0.1:8000"
  APP_ENV: testing
  DB_CONNECTION: sqlite
  DB_DATABASE: ":memory:"

jobs:
  phpunit:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, pdo, pdo_mysql, sqlite, pdo_sqlite, bcmath, json, xml, curl, zip
        coverage: none

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Prepare The Environment
      run: cp .env.example .env

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Install NPM dependencies
      run: npm ci

    - name: Build frontend assets
      run: npm run build

    - name: Run migrations
      run: php artisan migrate:fresh --force

    - name: Run PHPUnit Tests
      run: php artisan test --order-by=defects
      timeout-minutes: 10

    - name: Upload Console Logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: console-logs
        path: storage/logs
